name: Habari
favicon: null
layout_spectrum: 0.6995669689495116
typography_spectrum: 0.04158320254646242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ede9e8'
    - '#cec9c6'
    - '#0b0c07'
    - '#595051'
    - '#bca8a2'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
