name: Habari
favicon: null
layout_spectrum: 0.6995669689495116
typography_spectrum: 0.04158320254646242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9900598232634366
  lightness: 0.21843103971332312
  saturation: 0.6394990719854832
  rhythmicContrast: 0.5685612270608544
purpose: []
